language: python
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements.txt
- pip install coveralls
- mkdir -p tests/test_files
- git clone https://github.com/Rafiot/theZoo.git
- pushd theZoo/malwares/Binaries
- python unpackall.py
- popd
- mv theZoo/malwares/Binaries/out tests/test_files/
script:
- chmod +x ./run_tests.py ./setup.py
- python setup.py test
- python setup.py build
- python setup.py sdist
- python setup.py bdist
- python setup.py install
- coverage run --source=pefile --omit="*_test*,*__init__*,*test_lib*" ./run_tests.py
after_success:
- coveralls --verbose
addons:
  artifacts:
    debug: true
    paths:
    - $(git ls-files -o | grep .txt | grep -v pefile.egg-info | tr "\n" ":")
